name: lookmix_design_system
description: "A comprehensive design system for Lookmix projects including UI components and icons."
version: 0.0.1

homepage: https://github.com/joyjantiwaa/lookmix_design_system
repository: https://github.com/joyjantiwaa/lookmix_design_system

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  iconify_flutter: ^0.0.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.2.3
  flutter_portal: ^1.1.4
  intl: ^0.20.2
  collection: ^1.18.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  lucide_icons: ^0.257.0
  remixicon: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # ✅ ลบ storybook ออกถ้าพี่ลบโฟลเดอร์ example ไปแล้ว

flutter:
  uses-material-design: true
  assets:
    - assets/logos/Lookmixlogo.svg