name: lookmix_design_system
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  iconify_flutter: ^0.0.4  # สำคัญมากสำหรับไฟล์ไอคอนที่พี่แปลงมา
  google_fonts: ^6.1.0    # สำหรับระบบ Typography
  flutter_svg: ^2.2.3
  flutter_portal: ^1.1.4  # ✅ ใช้ตัวนี้แทนครับ
  intl: ^0.20.2           # สำหรับ Format วันที่
  collection: ^1.18.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  lucide_icons: 0.257.0
  remixicon: 1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # ตัวเลือกเสริมสำหรับทำ Storybook (แนะนำตัวนี้ครับ)
  storybook_flutter: ^0.14.0

flutter:
  uses-material-design: true

  # เพิ่มส่วนนี้เข้าไปครับ
  assets:
    - assets/logos/Lookmixlogo.svg